#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --config commitlint.config.cjs --edit 
npx --no -- commitlint --config commitlint.config.cjs --edit 
npx --no -- commitlint --config commitlint.config.cjs --edit 
